#!/bin/bash

function irc() {
    local terminal=

    if [[ "$( hostname -s )" == "secure" ]] ; then
        screen -R
    else
        if ( ! pstree -s $$ | grep -iq termi ) ; then
            terminal=${TERMINAL:-terminator}
        fi

        # terminator -T irssi -x mosh -- simon@psaux.de screen -x 2>/dev/null >&2
        # ${terminal:+$terminal -T irssi -x } ssh -t simon@secure.psaux.de -- screen -R
        ssh -t simon@secure.psaux.de -- screen -R
    fi
}

irc "$*"
