#!/bin/sh
export DEBIAN_FRONTEND=noninteractive
yes '' | LANG=C apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
yes '' | LANG=C apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

